version: '2'

services:

    autoland.treestatus:
        image: mozilla/autolandtreestatus
        restart: always

    autoland.hg:
        image: conduitteam/transplant-test-hgweb:10
        restart: always
        ports:
            - "${HOST_HGWEB}:80"
        volumes:
            - autoland-dev-hg:/repos

    autoland.db:
        image: postgres:10.1-alpine
        restart: always
        environment:
            POSTGRES_DB: autoland
            POSTGRES_USER: autoland
            POSTGRES_PASSWORD: autoland
        volumes:
            - autoland-dev-db:/var/lib/postgresql

    autoland.transplant-init:
        build: .
        command: init
        environment:
            SRC_PATH: /home/autoland/src
        depends_on:
            - autoland.hg
            - autoland.db
        volumes:
            - autoland-dev-repos:/repos
            - ./autoland:/home/autoland/src
        links:
            - autoland.db:autolanddb

    autoland.transplant-api:
        build: .
        restart: always
        command: api
        environment:
            SRC_PATH: /home/autoland/src
        depends_on:
            - autoland.hg
            - autoland.db
            - autoland.transplant-init
        ports:
            - "${HOST_AUTOLAND}:${PORT}"
        links:
            - autoland.db:autolanddb
            - autoland.hg:hgweb
        volumes:
            - ./autoland:/home/autoland/src

    autoland.transplant-daemon:
        build: .
        restart: always
        command: daemon
        environment:
            TREESTATUS_URL: "http://treestatus:${PORT}/%s"
            SRC_PATH: /home/autoland/src
        depends_on:
            - autoland.hg
            - autoland.db
            - autoland.transplant-init
        links:
            - autoland.db:autolanddb
            - autoland.hg:hgweb
            - autoland.treestatus:treestatus
        volumes:
            - ./autoland:/home/autoland/src

volumes:
    autoland-dev-hg:
    autoland-dev-db:
    autoland-dev-repos:
