---
- name: install packages required by autoland
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - ca-certificates
    - gcc
    - git
    - httpd
    - libffi
    - libffi-devel
    - libpqxx-devel
    - mod_ssl
    - mod_wsgi
    - openssh-clients
    - openssl-devel
    - postgresql
    - python-devel
    - python-pip
