---

# This can be overridden on the command line depending on where your
# secrets repo is located
# eg. ./deploy --seed --secrets-repo-path '../../secrets' --production
secrets_repo_path: "../../secrets/"

